development: &db
  adapter: mysql
  encoding: utf8
  database: cloth_app_dev
  username: ronaldpfeil
  password: trockenbau-ronaldpfeil
  host:     localhost

test:
  <<: *db
  database: cloth_app_test

production:
  <<: *db
  database: db_13811513n4
  username: user13811513n4
  password: cleecommunications
  host:     zeta.railshoster.de
